require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Default beautiful seed messages
const SEED_MESSAGES = [
  { text: "I hope you find the peace you are looking for.", theme: "sky" },
  { text: "We are all looking at the same sky, just from different places.", theme: "sky" },
  { text: "Some thoughts were meant to fly.", theme: "sky" },
  { text: "Let the rain wash away the things you cannot carry.", theme: "rain" },
  { text: "It's okay to feel sad sometimes. The clouds will clear eventually.", theme: "rain" },
  { text: "Not every feeling needs to stay with you.", theme: "rain" },
  { text: "Like a bottle in the ocean, I am just drifting along.", theme: "ocean" },
  { text: "The deepest oceans hold the quietest secrets.", theme: "ocean" },
  { text: "The sea remembers everything.", theme: "ocean" },
  { text: "Even in the darkest night, there is a star shining for you.", theme: "night" },
  { text: "We are all made of stardust, looking for a way home.", theme: "night" },
  { text: "Some lights travel very far.", theme: "night" }
];

// Determine if Supabase credentials are valid
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;
const isSupabaseConfigured = 
  supabaseUrl && 
  supabaseUrl !== 'your_supabase_project_url' && 
  supabaseKey && 
  supabaseKey !== 'your_supabase_anon_public_api_key';

let dbManager;

if (isSupabaseConfigured) {
  console.log('[Somewhere Backend] Initializing Supabase client...');
  const supabase = createClient(supabaseUrl, supabaseKey);

  dbManager = {
    async init() {
      try {
        // Query exact count of messages to verify connectivity and table existence
        const { count, error } = await supabase
          .from('messages')
          .select('id', { count: 'exact', head: true });

        if (error) {
          throw error;
        }

        // If table is empty, seed it
        if (count === 0) {
          console.log('[Somewhere Backend] Seeding Supabase database with default thoughts...');
          const { error: seedError } = await supabase.from('messages').insert(SEED_MESSAGES);
          if (seedError) console.error('[Somewhere Backend] Error seeding Supabase:', seedError);
        }
      } catch (err) {
        console.error('[Somewhere Backend] Supabase connection/initialization error:', err.message);
        console.error('[Somewhere Backend] Please verify your table structure in Supabase:');
        console.error('CREATE TABLE messages (id bigint generated by default as identity primary key, text text not null, theme text not null, created_at timestamp with time zone default timezone(\'utc\'::text, now()) not null);');
      }
    },

    async saveMessage({ text, theme }) {
      const { data, error } = await supabase
        .from('messages')
        .insert([{ text, theme }])
        .select();

      if (error) throw error;
      return data[0];
    },

    async getRandomMessage(theme) {
      let query = supabase.from('messages').select('id', { count: 'exact', head: true });
      if (theme) query = query.eq('theme', theme);

      const { count, error } = await query;
      if (error) throw error;
      if (!count) return null;

      const randomOffset = Math.floor(Math.random() * count);
      let fetchQuery = supabase.from('messages').select('*').limit(1).range(randomOffset, randomOffset);
      if (theme) fetchQuery = fetchQuery.eq('theme', theme);

      const { data, error: fetchError } = await fetchQuery;
      if (fetchError) throw fetchError;
      return data[0] || null;
    },

    async getStats() {
      const { count, error } = await supabase
        .from('messages')
        .select('id', { count: 'exact', head: true });

      if (error) throw error;
      return { total: count || 0 };
    }
  };
} else {
  console.warn('[Somewhere Backend] Warning: Supabase is not configured or using placeholders. Falling back to local SQLite...');
  const { DatabaseSync } = require('node:sqlite');
  const db = new DatabaseSync('fallback.db');

  dbManager = {
    async init() {
      db.exec(`
        CREATE TABLE IF NOT EXISTS messages (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          text TEXT NOT NULL,
          theme TEXT NOT NULL,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `);

      const countRow = db.prepare('SELECT COUNT(*) as count FROM messages').get();
      if (countRow.count === 0) {
        console.log('[Somewhere Backend] Seeding local SQLite database with default thoughts...');
        const insertStmt = db.prepare('INSERT INTO messages (text, theme) VALUES (?, ?)');
        for (const msg of SEED_MESSAGES) {
          insertStmt.run(msg.text, msg.theme);
        }
      }
    },

    async saveMessage({ text, theme }) {
      const insertStmt = db.prepare('INSERT INTO messages (text, theme) VALUES (?, ?)');
      const info = insertStmt.run(text, theme);
      return { id: info.lastInsertRowid, text, theme };
    },

    async getRandomMessage(theme) {
      let row;
      if (theme) {
        row = db.prepare('SELECT * FROM messages WHERE theme = ? ORDER BY RANDOM() LIMIT 1').get(theme);
      } else {
        row = db.prepare('SELECT * FROM messages ORDER BY RANDOM() LIMIT 1').get();
      }
      return row || null;
    },

    async getStats() {
      const stats = db.prepare('SELECT COUNT(*) as count FROM messages').get();
      return { total: stats.count };
    }
  };
}

// Initialize database
dbManager.init().then(() => {
  console.log('[Somewhere Backend] Database successfully initialized.');
});

// API Routes
app.post('/api/messages', async (req, res) => {
  const { text, theme } = req.body;
  if (!text || !theme) {
    return res.status(400).json({ error: 'Text and theme are required' });
  }
  try {
    const msg = await dbManager.saveMessage({ text, theme });
    res.json({ success: true, message: msg });
  } catch (err) {
    console.error('[API Error] POST /api/messages:', err.message);
    res.status(500).json({ error: 'Failed to save message', details: err.message });
  }
});

app.get('/api/messages/random', async (req, res) => {
  const { theme } = req.query;
  try {
    const msg = await dbManager.getRandomMessage(theme);
    res.json({ success: true, message: msg });
  } catch (err) {
    console.error('[API Error] GET /api/messages/random:', err.message);
    res.status(500).json({ error: 'Failed to retrieve message', details: err.message });
  }
});

app.get('/api/stats', async (req, res) => {
  try {
    const stats = await dbManager.getStats();
    res.json({ success: true, stats });
  } catch (err) {
    console.error('[API Error] GET /api/stats:', err.message);
    res.status(500).json({ error: 'Failed to retrieve stats', details: err.message });
  }
});

// Fallback index.html serving
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`[Somewhere Backend] Server is running on http://localhost:${PORT}`);
  });
}

module.exports = app;
